language: php

addons:
  chrome: stable

matrix:
  include:
  - php: 7.2
    env: TEST=e2e
  - php: 7.2
    env: TEST=resource-server
    env: CLIENT_ID=$RS_CLIENT_ID
  - php: 7.3
    env: TEST=e2e
  - php: 7.3
    env: TEST=resource-server
    env: CLIENT_ID=$RS_CLIENT_ID
  - php: 7.4
    env: TEST=e2e
  - php: 7.4
    env: TEST=resource-server
    env: CLIENT_ID=$RS_CLIENT_ID

install:
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - if [[ $TEST = 'resource=-server' ]]; then composer test:resource-server; fi
  - if [[ $TEST = 'e2e' ]]; then composer test:e2e; fi

notifications:
  slack:
    rooms:
      - okta:dtcmG9Sqx3PpnEthGwfEmlnu#eng-devex_alerts
    on_pull_requests: false
    on_success: never
    on_failure: always
